In [2]:
from nilearn.datasets import fetch_atlas_harvard_oxford, fetch_development_fmri

dataset = fetch_atlas_harvard_oxford("cort-maxprob-thr25-2mm")
atlas_filename = dataset.maps
labels = dataset.labels

print(f"Atlas ROIs are located in nifti image (4D) at: {atlas_filename}")

# One subject of brain development fMRI data
data = fetch_development_fmri(n_subjects=1, reduce_confounds=True)
fmri_filenames = data.func[0]
reduced_confounds = data.confounds[0]  # This is a preselected set of confounds

[get_dataset_dir] Dataset found in /home/dxj180007/nilearn_data/fsl
Atlas ROIs are located in nifti image (4D) at:
<class 'nibabel.nifti1.Nifti1Image'>
data shape (91, 109, 91)
affine:
[[   2.    0.    0.  -90.]
 [   0.    2.    0. -126.]
 [   0.    0.    2.  -72.]
 [   0.    0.    0.    1.]]
metadata:
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : np.bytes_(b'')
db_name         : np.bytes_(b'')
extents         : 0
session_error   : 0
regular         : np.bytes_(b'r')
dim_info        : 0
dim             : [  3  91 109  91   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : uint8
bitpix          : 8
slice_start     : 0
pixdim          : [1. 2. 2. 2. 1. 1. 1. 1.]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max         : 48.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : np.bytes_(b'FSL3.3')
aux_file        : np.bytes_(b'MGH-Cortical')
qform_code      : unknown
sform_code      : aligned
quatern_b       : 0.0
quatern_c       : 0.0
quatern_d       : 0.0
qoffset_x       : -90.0
qoffset_y       : -126.0
qoffset_z       : -72.0
srow_x          : [  2.   0.   0. -90.]
srow_y          : [   0.    2.    0. -126.]
srow_z          : [  0.   0.   2. -72.]
intent_name     : np.bytes_(b'')
magic           : np.bytes_(b'n+1')

[get_dataset_dir] Dataset created in /home/dxj180007/nilearn_data/development_fmri
[_add_readme_to_default_data_locations] Added README.md to /home/dxj180007/nilearn_data/development_fmri
[get_dataset_dir] Dataset created in /home/dxj180007/nilearn_data/development_fmri/development_fmri
[fetch_single_file] Downloading data from https://osf.io/yr3av/download ...
[fetch_single_file]  ...done. (2 seconds, 0 min)

[get_dataset_dir] Dataset found in /home/dxj180007/nilearn_data/development_fmri/development_fmri
[fetch_single_file] Downloading data from https://osf.io/download/5c8ff3df4712b400183b7092/ ...
[fetch_single_file]  ...done. (2 seconds, 0 min)

[fetch_single_file] Downloading data from https://osf.io/download/5c8ff3e04712b400193b5bdf/ ...
[fetch_single_file]  ...done. (1 seconds, 0 min)

In [3]:
data.confounds[0]

'/home/dxj180007/nilearn_data/development_fmri/development_fmri/sub-pixar123_task-pixar_desc-reducedConfounds_regressors.tsv'

In [4]:
data.func[0]

'/home/dxj180007/nilearn_data/development_fmri/development_fmri/sub-pixar123_task-pixar_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz'

In [5]:
from nilearn.interfaces.fmriprep import load_confounds

confounds_simple, sample_mask = load_confounds(
    fmri_filenames,
    strategy=["high_pass", "motion", "wm_csf"],
    motion="basic",
    wm_csf="basic",
)

print("The shape of the confounds matrix is:", confounds_simple.shape)
print(confounds_simple.columns)

The shape of the confounds matrix is: (168, 12)
Index(['cosine00', 'cosine01', 'cosine02', 'cosine03', 'csf', 'rot_x', 'rot_y',
       'rot_z', 'trans_x', 'trans_y', 'trans_z', 'white_matter'],
      dtype='object')

In [6]:
confounds_simple

,cosine00,cosine01,cosine02,cosine03,csf,rot_x,rot_y,rot_z,trans_x,trans_y,trans_z,white_matter
0,0.109104,0.109090,0.109066,0.109033,-2.675004,0.000304,0.000583,0.000201,0.006621,-0.026078,0.055006,-0.876886
1,0.109066,0.108937,0.108723,0.108423,-2.902773,-0.000316,0.000418,0.000135,0.000668,-0.027587,0.049458,-1.418909
2,0.108990,0.108632,0.108038,0.107207,-2.629915,-0.000285,0.000595,0.000076,0.006628,-0.019085,0.075787,-1.540842
3,0.108875,0.108176,0.107012,0.105391,-1.601793,-0.000226,0.001049,0.000041,0.009347,-0.023900,0.053022,-1.922085
4,0.108723,0.107567,0.105651,0.102986,-2.258970,-0.000245,0.000779,0.000042,0.006629,-0.033396,0.077764,-1.843388
...,...,...,...,...,...,...,...,...,...,...,...,...
163,-0.108723,0.107567,-0.105651,0.102986,2.445759,-0.000299,-0.000335,0.000276,-0.010477,0.064873,-0.022169,1.221217
164,-0.108875,0.108176,-0.107012,0.105391,2.244003,0.000406,-0.000279,-0.000007,-0.012250,-0.064266,-0.042248,1.237783
165,-0.108990,0.108632,-0.108038,0.107207,3.390256,-0.000163,-0.000574,0.000091,-0.004304,0.053241,-0.029500,1.590905
166,-0.109066,0.108937,-0.108723,0.108423,3.485434,0.000857,-0.000557,0.000046,-0.008227,-0.081559,-0.034236,1.122246
167,-0.109104,0.109090,-0.109066,0.109033,0.402734,-0.000428,-0.000256,0.000075,-0.020041,0.069287,-0.007294,1.000828

In [11]:
confounds_path = '/mfs/io/groups/dmello/projects/cerebellum_reliability/derivatives/fmriprep/ds000224/sub-MSC01/ses-func01/func/sub-MSC01_ses-func01_task-rest_desc-confounds_timeseries.tsv'
import pandas as pd

confounds = pd.read_csv(
                confounds_path,
                sep='\t', 
                on_bad_lines='skip',
                encoding='latin-1',
                engine='python',
                # usecols=selected_cols,
                header=0
                )

In [12]:
confounds

,global_signal,global_signal_derivative1,global_signal_power2,global_signal_derivative1_power2,csf,csf_derivative1,csf_derivative1_power2,csf_power2,white_matter,white_matter_derivative1,...,motion_outlier54,motion_outlier55,motion_outlier56,motion_outlier57,motion_outlier58,motion_outlier59,motion_outlier60,motion_outlier61,motion_outlier62,motion_outlier63
0,577.207735,NaN,333168.768891,NaN,667.217011,NaN,NaN,445178.540224,601.446138,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,574.276267,-2.931468,329793.230701,8.593503,653.783990,-13.433022,180.446071,427433.505144,601.270557,-0.175580,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,572.937320,-1.338947,328257.172536,1.792779,648.049999,-5.733991,32.878650,419968.801048,601.074486,-0.196072,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,572.563501,-0.373819,327828.962186,0.139741,648.693211,0.643212,0.413722,420802.882095,600.924345,-0.150141,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,571.209067,-1.354434,326279.797744,1.834491,643.731713,-4.961498,24.616460,414390.518769,601.090348,0.166003,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813,570.254140,-1.227154,325189.784267,1.505907,632.019244,-0.095981,0.009212,399448.325284,601.107068,-1.596426,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
814,570.380263,0.126123,325333.644000,0.015907,629.830828,-2.188416,4.789164,396686.872448,602.361571,1.254503,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
815,570.064820,-0.315442,324973.899561,0.099504,631.069008,1.238180,1.533089,398248.093218,601.246654,-1.114916,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
816,569.509288,-0.555532,324340.829601,0.308616,632.093824,1.024816,1.050247,399542.602246,600.453928,-0.792726,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
817,569.204007,-0.305282,323993.201189,0.093197,632.864286,0.770462,0.593611,400517.204034,601.359225,0.905297,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
selected_cols = ['cosine00', 'cosine01', 'cosine02', 'cosine03', 'csf', 'rot_x', 'rot_y',
    'rot_z', 'trans_x', 'trans_y', 'trans_z', 'white_matter']

In [14]:
confounds[selected_cols]

,cosine00,cosine01,cosine02,cosine03,csf,rot_x,rot_y,rot_z,trans_x,trans_y,trans_z,white_matter
0,0.000000,0.000000,0.000000,0.000000,667.217011,0.000928,0.000483,0.000000,-0.012188,0.009673,-0.003498,601.446138
1,0.000000,0.000000,0.000000,0.000000,653.783990,0.000103,-0.000000,0.000000,0.016647,-0.038033,0.025174,601.270557
2,0.000000,0.000000,0.000000,0.000000,648.049999,-0.000575,0.000414,0.000000,-0.000020,0.133633,0.021402,601.074486
3,0.049538,0.049537,0.049537,0.049536,648.693211,0.000347,0.000257,0.000057,0.015622,-0.035520,0.081380,600.924345
4,0.049537,0.049534,0.049530,0.049524,643.731713,-0.000575,0.000147,0.000000,0.008935,0.030041,0.071265,601.090348
...,...,...,...,...,...,...,...,...,...,...,...,...
813,-0.049530,0.049508,-0.049471,0.049419,632.019244,0.011416,0.018778,0.009044,0.420973,-0.617693,1.846700,601.107068
814,-0.049533,0.049520,-0.049497,0.049466,629.830828,0.009947,0.019377,0.009044,0.452850,-0.466462,1.802690,602.361571
815,-0.049535,0.049529,-0.049517,0.049501,631.069008,0.011928,0.021003,0.009758,0.456752,-0.798497,1.950240,601.246654
816,-0.049537,0.049534,-0.049530,0.049524,632.093824,0.011523,0.021132,0.009713,0.432376,-0.695100,2.085430,600.453928
817,-0.049538,0.049537,-0.049537,0.049536,632.864286,0.011341,0.021415,0.009643,0.449061,-0.524492,2.003220,601.359225